<a href="https://colab.research.google.com/github/PavanPk1/MyPractice_Colab_notebooks/blob/main/chi_square_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import chi2
from scipy.stats import chi2_contingency

In [4]:
data = pd.read_csv('adult_dataset.csv')
data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [6]:
data.nunique()

age                   74
workclass              9
fnlwgt             28523
education             16
educational-num       16
marital-status         7
occupation            15
relationship           6
race                   5
gender                 2
capital-gain         123
capital-loss          99
hours-per-week        96
native-country        42
income                 2
dtype: int64

In [7]:
data.gender.value_counts()

gender
Male      32650
Female    16192
Name: count, dtype: int64

In [8]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
?                    2809
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [9]:
print(data.groupby('occupation')['gender'].value_counts())

occupation         gender
?                  Male      1536
                   Female    1273
Adm-clerical       Female    3769
                   Male      1842
Armed-Forces       Male        15
Craft-repair       Male      5789
                   Female     323
Exec-managerial    Male      4338
                   Female    1748
Farming-fishing    Male      1395
                   Female      95
Handlers-cleaners  Male      1818
                   Female     254
Machine-op-inspct  Male      2218
                   Female     804
Other-service      Female    2698
                   Male      2225
Priv-house-serv    Female     228
                   Male        14
Prof-specialty     Male      3930
                   Female    2242
Protective-serv    Male       861
                   Female     122
Sales              Male      3557
                   Female    1947
Tech-support       Male       884
                   Female     562
Transport-moving   Male      2228
                   Female     127
Name: count, dtype: int64

In [14]:
pd.crosstab(data.occupation, data.gender, margins = True)

gender             Female   Male    All
occupation
?                    1273   1536   2809
Adm-clerical         3769   1842   5611
Armed-Forces            0     15     15
Craft-repair          323   5789   6112
Exec-managerial      1748   4338   6086
Farming-fishing        95   1395   1490
Handlers-cleaners     254   1818   2072
Machine-op-inspct     804   2218   3022
Other-service        2698   2225   4923
Priv-house-serv       228     14    242
Prof-specialty       2242   3930   6172
Protective-serv       122    861    983
Sales                1947   3557   5504
Tech-support          562    884   1446
Transport-moving      127   2228   2355
All                 16192  32650  48842

In [11]:
observed = pd.crosstab(data.occupation, data.gender)
observed

gender             Female  Male
occupation
?                    1273  1536
Adm-clerical         3769  1842
Armed-Forces            0    15
Craft-repair          323  5789
Exec-managerial      1748  4338
Farming-fishing        95  1395
Handlers-cleaners     254  1818
Machine-op-inspct     804  2218
Other-service        2698  2225
Priv-house-serv       228    14
Prof-specialty       2242  3930
Protective-serv       122   861
Sales                1947  3557
Tech-support          562   884
Transport-moving      127  2228

In [12]:
# chi2 test_statistic, p-value, degrees of freedom, expected_frequences
result = chi2_contingency(observed)
result

Chi2ContingencyResult(statistic=np.float64(8789.50801388705), pvalue=np.float64(0.0), dof=14, expected_freq=array([[ 931.233938  , 1877.766062  ],
       [1860.14725032, 3750.85274968],
       [   4.97276934,   10.02723066],
       [2026.2377462 , 4085.7622538 ],
       [2017.61827935, 4068.38172065],
       [ 493.96175423,  996.03824577],
       [ 686.90520454, 1385.09479546],
       [1001.8472626 , 2020.1527374 ],
       [1632.06289669, 3290.93710331],
       [  80.22734532,  161.77265468],
       [2046.12882355, 4125.87117645],
       [ 325.88215061,  657.11784939],
       [1824.67482904, 3679.32517096],
       [ 479.37496417,  966.62503583],
       [ 780.72478604, 1574.27521396]]))

In [18]:
chi2_test_stat = result[0]
deg_freedom = result[2]
expected_freq = result[3]

print(f"Chi-square test : {chi2_test_stat}")
print(f"Degrees of freedom: {deg_freedom}")

Chi-square test : 8789.50801388705
Degrees of freedom: 14

In [20]:
#checking
print(2809*16192 / 48842)
print(5611*16192 / 48842)
print(2809*32650 / 48842)
print(5611*32650 / 48842)

931.2339380041767
1860.1472503173497
1877.7660619958233
3750.85274968265

In [21]:
alpha = 0.05
chi2_critical = chi2.ppf(alpha, deg_freedom)
chi2_critical

np.float64(6.57063138378934)

In [23]:
print(chi2_test_stat)

8789.50801388705

In [24]:
if chi2_test_stat > chi2_critical:
    print('Reject Null Hypothesis')
else:
    print('Failed to reject Null Hypothesis')

Reject Null Hypothesis

## Education and Gender

In [25]:
data.education.unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [26]:
pd.crosstab(data.education, data.gender, margins = True)

gender        Female   Male    All
education
10th             457    932   1389
11th             650   1162   1812
12th             211    446    657
1st-4th           61    186    247
5th-6th          127    382    509
7th-8th          239    716    955
9th              220    536    756
Assoc-acdm       627    974   1601
Assoc-voc        734   1327   2061
Bachelors       2477   5548   8025
Doctorate        113    481    594
HS-grad         5097  10687  15784
Masters          845   1812   2657
Preschool         24     59     83
Prof-school      132    702    834
Some-college    4178   6700  10878
All            16192  32650  48842

In [27]:
print(1389*16192/48842)

460.47844068629456

In [28]:
observed = pd.crosstab(data.education, data.gender)
observed

gender        Female   Male
education
10th             457    932
11th             650   1162
12th             211    446
1st-4th           61    186
5th-6th          127    382
7th-8th          239    716
9th              220    536
Assoc-acdm       627    974
Assoc-voc        734   1327
Bachelors       2477   5548
Doctorate        113    481
HS-grad         5097  10687
Masters          845   1812
Preschool         24     59
Prof-school      132    702
Some-college    4178   6700

In [29]:
# chi2 test_statistic, p-value, degrees of freedom, expected_frequences
result = chi2_contingency(observed)
chi2_test_stat = result[0]
deg_freedom = result[2]
expected_freq = result[3]
result

Chi2ContingencyResult(statistic=np.float64(424.7053110654286), pvalue=np.float64(4.401401289798295e-81), dof=15, expected_freq=array([[  460.47844069,   928.52155931],
       [  600.71053601,  1211.28946399],
       [  217.807297  ,   439.192703  ],
       [   81.8849351 ,   165.1150649 ],
       [  168.74263953,   340.25736047],
       [  316.59964784,   638.40035216],
       [  250.62757463,   505.37242537],
       [  530.76024733,  1070.23975267],
       [  683.25850702,  1377.74149298],
       [ 2660.43159576,  5364.56840424],
       [  196.92166578,   397.07833422],
       [ 5232.67941526, 10551.32058474],
       [  880.84320871,  1776.15679129],
       [   27.51599034,    55.48400966],
       [  276.48597519,   557.51402481],
       [ 3606.25232382,  7271.74767618]]))

In [30]:
alpha = 0.05
chi2_critical = chi2.ppf(alpha, deg_freedom)
chi2_critical

np.float64(7.2609439276700325)

In [31]:
if chi2_test_stat > chi2_critical:
    print('Reject Null Hypothesis')
else:
    print('Failed to reject Null Hypothesis')

Reject Null Hypothesis

### Effect of significance level and degree of freedom

In [33]:
for i in [0.05, 0.1, 0.5, 0.99]: #significance level's
    for j in range(1,30,5): #degree of freedom
        print('For Significance Level : {} and Degree of Freedom : {} Chi2 Critical is = {}'.format(i,j,chi2.ppf(i,j)))
    print()

For Significance Level : 0.05 and Degree of Freedom : 1 Chi2 Critical is = 0.003932140000019522
For Significance Level : 0.05 and Degree of Freedom : 6 Chi2 Critical is = 1.6353828943279067
For Significance Level : 0.05 and Degree of Freedom : 11 Chi2 Critical is = 4.574813079322224
For Significance Level : 0.05 and Degree of Freedom : 16 Chi2 Critical is = 7.9616455723785515
For Significance Level : 0.05 and Degree of Freedom : 21 Chi2 Critical is = 11.591305208820733
For Significance Level : 0.05 and Degree of Freedom : 26 Chi2 Critical is = 15.379156583261723

For Significance Level : 0.1 and Degree of Freedom : 1 Chi2 Critical is = 0.01579077409343122
For Significance Level : 0.1 and Degree of Freedom : 6 Chi2 Critical is = 2.2041306564986427
For Significance Level : 0.1 and Degree of Freedom : 11 Chi2 Critical is = 5.577784789799852
For Significance Level : 0.1 and Degree of Freedom : 16 Chi2 Critical is = 9.312236353796006
For Significance Level : 0.1 and Degree of Freedom : 21 Chi2 Critical is = 13.239597975395304
For Significance Level : 0.1 and Degree of Freedom : 26 Chi2 Critical is = 17.29188498973876

For Significance Level : 0.5 and Degree of Freedom : 1 Chi2 Critical is = 0.454936423119572
For Significance Level : 0.5 and Degree of Freedom : 6 Chi2 Critical is = 5.348120627447118
For Significance Level : 0.5 and Degree of Freedom : 11 Chi2 Critical is = 10.340998074391827
For Significance Level : 0.5 and Degree of Freedom : 16 Chi2 Critical is = 15.338498885001608
For Significance Level : 0.5 and Degree of Freedom : 21 Chi2 Critical is = 20.337227563547934
For Significance Level : 0.5 and Degree of Freedom : 26 Chi2 Critical is = 25.336458117477264

For Significance Level : 0.99 and Degree of Freedom : 1 Chi2 Critical is = 6.6348966010212145
For Significance Level : 0.99 and Degree of Freedom : 6 Chi2 Critical is = 16.811893829770927
For Significance Level : 0.99 and Degree of Freedom : 11 Chi2 Critical is = 24.724970311318277
For Significance Level : 0.99 and Degree of Freedom : 16 Chi2 Critical is = 31.999926908815176
For Significance Level : 0.99 and Degree of Freedom : 21 Chi2 Critical is = 38.93217268351607
For Significance Level : 0.99 and Degree of Freedom : 26 Chi2 Critical is = 45.64168266628317

* we can conclude that with increase in significance level and degrees of freedom chi2 critical will also increase

* for a fixed df, increasing the significance level increases the critical value.